# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Npm@1
  inputs:
    command: 'install'
    
- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'default'
    enableCodeCoverage: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build/pck'
    ArtifactName: 'drop'
    publishLocation: 'Container'
