name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        working-directory: ./source/
        
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true

    - name: Restore dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore

    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --no-restore

    - name: Test
      working-directory: ${{env.working-directory}}
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
